package com.archer.note.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteTypeDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final NoteTypeDao noteTypeDao;
    private final NoteDao noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteTypeDaoConfig = daoConfigMap.get(NoteTypeDao.class).clone();
        noteTypeDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteTypeDao = new NoteTypeDao(noteTypeDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(NoteType.class, noteTypeDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        noteTypeDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
    }

    public NoteTypeDao getNoteTypeDao() {
        return noteTypeDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
